### ISSUE TITLE
Keyboard events are handled twice and from different view models

### ISSUE THREAD

**Issue by stevenengland** [stevenengland/FinCalcR#6]
If a control of the fincalc vm has the focus and a key is pressed it gets handled twice. The reason is that there are two handlers active. One from the shellview and one from the fincalc view.
Furthermore even if the user is on another view than the fincalc view the keyboard presses are still handled within the fincalc viewmodel. The reason is that the global handler in the shellview passes the keys via eventaggregation the every subscriber no matter which view is currently active.

**Comment by mokkin** [comment]
I can confirm this via numpad and regular keys.

**Comment by stevenengland** [comment]
fixed
