### ISSUE TITLE
ESC button not implemented

### ISSUE THREAD

**Issue by mokkin** [stevenengland/FinCalcR#8]
The Escape button should be implemented to clear the cache.
This is not essential, but doesn't break the workflow while using the calculator via keyboard.

**Comment by stevenengland** [comment]
Hi @mokkin - Please see https://github.com/stevenengland/FinCalcR/blob/master/docs/Keyboard_en.MD the available key combinations. The functionality you're looking for is covered by DEL key. I will add the ESC key in a upcoming version as well.
